---

- name: Copy install_chrome.ps1 script to target server
  win_copy:
    src: install_chrome.ps1
    dest: C:\Users\Administrator\Desktop\install_chrome.ps1

- name: Execute install_chrome.ps1 script to install Chrome
  win_command: powershell.exe -ExecutionPolicy Bypass -File C:\Users\Administrator\Desktop\install_chrome.ps1

